---
title: "Untitled"
author: "Gordon Blasco"
date: "5/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library(patchwork)
library(ggpubr)
library(rworldmap)
source("~/github/aquaculture/src/directories.R") # Sets file directories 

fao_production <- read_csv(file.path(dir_raw_data, "/FAO/production/TS_FI_PRODUCTION.csv")) # Raw fao data
fao_species    <- read_csv(file.path(dir_raw_data, "/FAO/production/CL_FI_SPECIES_GROUPS.csv")) %>% # Species ref
  rename(SPECIES = "3Alpha_Code")
fao_country    <- read_csv(file.path(dir_raw_data, "/FAO/production/CL_FI_COUNTRY_GROUPS.csv")) # Species ref
fao_neis       <- read_csv("data/nei_codes.csv")

freshwater <- fao_production %>% 
  distinct(SPECIES) %>% 
  left_join(fao_species) %>% 
  filter(ISSCAAP_Group == "Miscellaneous freshwater fishes"|
         ISSCAAP_Group == "Freshwater crustaceans"|
         CPC_Class     == "Freshwater fish, live, fresh or chilled"|
         ISSCAAP_Group == "Freshwater molluscs"|
         SPECIES       == "FSH"|
         SPECIES       == "QEX"|
         SPECIES       == "QPD") %>% 
  pull(SPECIES)

spp_info <- fao_production %>% 
  distinct(SPECIES) %>% 
  left_join(fao_species) %>% 
  left_join(fao_neis) %>% 
  mutate(is_freshwater = if_else(SPECIES %in% freshwater, "freshwater", "marine"))

```

```{r}
over_time <- fao_production %>% 
  filter(SOURCE == 4) %>% 
  left_join(spp_info) %>% 
  filter(excluded == "included") %>% 
  group_by(YEAR, id_level,) %>% 
  summarise(
    total = sum(QUANTITY, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  pivot_wider(names_from = id_level, values_from = total) %>% 
  mutate(total = Species + Nei, 
         prop_nei = (Nei / total))

ggplot(over_time, aes(x = YEAR, y = Nei))+
  geom_point()+
  geom_line()

prop_plot <- ggplot(over_time, aes(x = YEAR, y = prop_nei))+
  geom_point()+
  geom_line()+
  labs(
    x = "Year", 
    y = "Proportion NEI"
  )

lm_growth_prop <- lm(formula = prop_nei ~ YEAR, over_time)
tidy(lm_growth_prop)
summ(lm_growth_prop)

lm_total_prop <- lm(formula = Nei ~ YEAR, over_time)
tidy(lm_total_prop)
summ(lm_total_prop)
```

```{r}
by_country <- fao_production %>% 
  filter(SOURCE == 4) %>% 
  left_join(spp_info) %>% 
  group_by(YEAR, COUNTRY, id_level) %>% 
  summarise(
    total = sum(QUANTITY, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  pivot_wider(names_from = id_level, values_from = total) %>% 
  mutate(Nei = if_else(is.na(Nei), 0 , Nei),
         Species = if_else(is.na(Species), 0 , Species)) %>% 
  filter(!(Nei == 0 & Species == 0)) %>% 
  mutate(total = Species + Nei, 
         prop_nei = (Nei / total)*100) %>% 
  mutate(prop_nei = if_else(Nei == 0, 0, prop_nei))

median <- by_country %>% 
  group_by(YEAR) %>% 
  summarise(
    median_prop_nei = median(prop_nei)
  ) %>% 
  ungroup()

ggplot(median, aes(x = YEAR, y = median_prop_nei))+
  geom_point()+
  geom_line()

ggplot(by_country, aes(x = YEAR, y = prop_nei, group = YEAR))+
  geom_boxplot()

lm_median <- lm(formula = median_prop_nei ~ YEAR, data = median)
tidy(lm_median)
summ(lm_median)

confint(lm_median, level = 0.95)
```

```{r}
country_prep <- fao_country %>% 
  select(UN_Code, Continent_Group) %>% 
  #mutate(Continent_Group = if_else(UN_Code == 156, "China", Continent_Group)) %>% 
  rename(
    COUNTRY = UN_Code,
    region  = Continent_Group
  ) %>% 
  distinct(COUNTRY, .keep_all = TRUE) %>% 
  filter(!(is.na(region))) 
  


country_contrib <- fao_production %>% 
  filter(SOURCE == 4) %>% 
  left_join(spp_info) %>% 
  left_join(., country_prep) %>% 
  filter(!(is.na(region))) %>% 
  filter(id_level == "Nei") %>% 
  group_by(YEAR, region) %>% 
  summarise(
    nei_total = sum(QUANTITY, na.rm = TRUE)
  ) %>% 
  mutate(percentage = nei_total / sum(nei_total)) %>% 
  ungroup()

country_order <- country_contrib %>% 
  filter(YEAR == 2016) %>% 
  arrange(-percentage) %>% 
  pull(region)
country_contrib$region_new <- ordered(country_contrib$region, levels =country_order)


ggplot(country_contrib, aes(x=YEAR, y=percentage, fill=region_new)) + 
    geom_area(alpha=0.6 , size=1, colour="black")

```

plot it up
```{r}
prop_plot <- ggplot(over_time, aes(x = YEAR, y = prop_nei))+
  geom_point()+
  geom_line()+
  geom_smooth(method = "lm", color = "gray40")+
  labs(
    x = "Year", 
    y = "Proportion NEI",
    title = "A) Global Proportion of NEI Resolved Catch"
  )+
  ggpubr::theme_pubclean()+
  scale_x_continuous(expand = c(0,0))+
  theme(
    axis.title.x = element_blank(),
    text = element_text(family = 'serif'),
    plot.title.position = "plot"
   )

box_plot <- ggplot(by_country, aes(x = YEAR, y = prop_nei, group = YEAR))+
  geom_boxplot()+
  ggpubr::theme_pubclean()+
  labs(
    x = "Year", 
    y = "Proportion NEI",
    title = "B) Median of NEI Resolved Catch for All Reporting Countries"
  )+
  scale_x_continuous(expand = c(0,0))+
   theme(
    axis.title.x = element_blank(),
    text = element_text(family = 'serif'),
    plot.title.position = "plot"
   )

by_region <- ggplot(country_contrib, aes(x=YEAR, y=percentage, fill=region_new)) + 
    geom_area(alpha=0.6 , size=1, colour="black")+
  ggpubr::theme_pubclean()+
  labs(
    x = "Year", 
    y = "% NEI Contribution",
    title = "C) Percent Contribution by Region"
  )+
  scale_x_continuous(expand = c(0,0))+
   theme(
    text = element_text(family = 'serif'),
    plot.title.position = "plot",
    legend.title = element_blank()
   )
 

figure_2 <- prop_plot/box_plot/by_region &
  labs_pubr(base_size = 16)&
  theme(plot.title.position = "plot",
        legend.title = element_blank(),
        axis.title.y = element_text(size = 11),
        axis.title.x = element_blank())

ggsave(plot = figure_2, filename = "figures/figure_2.png", device = "png")

```

